spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    # url: jdbc:mysql://localhost:3306/microservice_mallmanagement?serverTimezone=UTC&useSSL=false&characterEncoding=UTF-8
    #与docker整合时可以使用以下配置（也可以使用具体的IP+端口）
    url: jdbc:mysql://mysql:3306/microservice_mallmanagement
    username: root
    password: 123456
  application:
    name: user-service
  cloud:
    inetutils:
      preferred-networks:
      - 10.0
server:
  port: 8030 #指定Eureka实例的端口号
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      # defaultZone: http://localhost:8761/eureka/
      #上线测试使用一下配置
      defaultZone: http://eureka-server:8761/eureka/
ORDERSERVICEURL: http://order-service/
